name: Build

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::878145708291:role/GithubActions
          aws-region: eu-west-1

      - name: Get CodeArtifact token
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain my-domain \
            --domain-owner 878145708291 \
            --region eu-west-1 \
            --query authorizationToken \
            --output text)" >> "$GITHUB_ENV"
            
      - name: Get CodeArtifact endpoint
        run: |
          echo "CODEARTIFACT_MAVEN_URL=$(aws codeartifact get-repository-endpoint \
            --domain my-domain \
            --domain-owner 878145708291 \
            --repository codeartifact-demo \
            --format maven \
            --region eu-west-1 \
            --query repositoryEndpoint \
            --output text)" >> "$GITHUB_ENV"
      - name: Configure Maven
        run: |
          mkdir -p ~/.m2

          cat > ~/.m2/settings.xml <<EOF
          <settings>
           <servers>
            <server>
              <id>codeartifact</id>
              <username>aws</username>
              <password>$CODEARTIFACT_AUTH_TOKEN</password>
            </server>
           </servers>

           <profiles>
            <profile>
            <id>codeartifact</id>
            <repositories>
             <repository>
              <id>codeartifact</id>
              <url>$CODEARTIFACT_MAVEN_URL</url>
             </repository>
             </repositories>
            </profile>
           </profiles>

            <activeProfiles>
             <activeProfile>codeartifact</activeProfile>
            </activeProfiles>
          </settings>
          EOF


      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        run: mvn clean package
